Changed libxbee to install header files to the target directory

diff --git a/fsl-community-bsp/build/tmp/work/wandboard_dual-poky-linux-gnueabi/core-image-wvsnp-minimal/1.0-r0/rootfs/etc/init.d/hostapd b/fsl-community-bsp/build/tmp/work/wandboard_dual-poky-linux-gnueabi/core-image-wvsnp-minimal/1.0-r0/rootfs/etc/init.d/hostapd
--- a/fsl-community-bsp/build/tmp/work/wandboard_dual-poky-linux-gnueabi/core-image-wvsnp-minimal/1.0-r0/rootfs/etc/init.d/hostapd
+++ b/fsl-community-bsp/build/tmp/work/wandboard_dual-poky-linux-gnueabi/core-image-wvsnp-minimal/1.0-r0/rootfs/etc/init.d/hostapd
@@ -6,15 +6,24 @@ ARGS="/etc/hostapd.conf -B"
 
 test -f $DAEMON || exit 0
 
-[ -r /etc/default/hostapd ] && . /etc/default/hostapd
-
 set -e
 
-case "$HOSTAPD_ENABLE" in
-	[Nn]*)
-		exit 0
-		;;
-esac
+# source function library
+. /etc/init.d/functions
+
+delay_stop() {
+	count=0
+	while [ $count -lt 9 ] ; do
+	        if pidof $DAEMON >/dev/null; then
+	                sleep 1
+	        else
+	                return 0
+	        fi
+		count=`expr $count + 1`
+	done
+	echo "Failed to stop $DESC."
+	return 1
+}
 
 case "$1" in
     start)
@@ -24,20 +33,24 @@ case "$1" in
 	;;
     stop)
 	echo -n "Stopping $DESC: "
-	start-stop-daemon -K -x $DAEMON
+	start-stop-daemon -K --oknodo -x $DAEMON
 	echo "$NAME."
 	;;
     restart)
 	$0 stop
-	$0 start
+	delay_stop && $0 start
 	;;
     reload)
 	echo -n "Reloading $DESC: "
 	killall -HUP $(basename ${DAEMON})
 	echo "$NAME."
 	;;
+    status)
+	status $DAEMON
+	exit $?
+	;;
     *)
-	echo "Usage: $0 {start|stop|restart|reload}"
+	echo "Usage: $0 {start|stop|restart|reload|status}"
 	exit 1
 	;;
 esac
